services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo:
    image: rnium/supplies
    container_name: odoo-app
    depends_on:
      - db
    ports:
      - "8017"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - DATABASE=postgres
    volumes:
      - .:/mnt/extra-addons/supplies
      - ./odoo.conf:/etc/odoo/odoo.conf:ro
      - odoo-data:/var/lib/odoo

  nginx:
    image: nginx:alpine
    container_name: nginx-server
    depends_on:
      - odoo
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  odoo-db-data:
  odoo-data: